name: release-assets
on: [push]
jobs:
  build-linux-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build linux asset
        shell: pwsh
        run: ./build-on-linux.ps1
      - name: Upload linux asset
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets/standalone-linux-64.zip
  build-windows-asset:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build windows asset
        shell: pwsh
        run: ./build-on-windows.ps1
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --verbosity normal
      - name: Upload windows asset
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets/standalone-windows-64.zip
  release-asset:
    runs-on: ubuntu-latest
    needs: [build-linux-asset, build-windows-asset]
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.1
          release_name: Release 0.0.1
          draft: true
          prerelease: true
      - name: Download assets
        uses: actions/download-artifact@v3
        with:
          name: assets
      - name: Upload release asset linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: standalone-linux-64.zip
          asset_name: standalone-linux-64.zip
          asset_content_type: application/zip
      - name: Upload release asset windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: standalone-windows-64.zip
          asset_name: standalone-windows-64.zip
          asset_content_type: application/zip
  