name: release-assets
on: [push]
env:
  VERSION: 0.0.2
jobs:
  build-linux-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build linux asset
        shell: pwsh
        run: ./build-on-linux.ps1
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --verbosity normal
        working-directory: ./src/Weasyprint.Wrapped.Tests
      - name: Upload linux asset
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets/standalone-linux-64.zip
  build-windows-asset:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build windows asset
        shell: pwsh
        run: ./build-on-windows.ps1
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --verbosity normal
        working-directory: ./src/Weasyprint.Wrapped.Tests
      - name: Upload windows asset
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: ./assets/standalone-windows-64.zip
  release-asset:
    runs-on: ubuntu-latest
    needs: [build-linux-asset, build-windows-asset]
    steps:
      - uses: actions/checkout@v3
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $VERSION
          release_name: Release $VERSION
          draft: true
          prerelease: true
      - name: Download assets
        uses: actions/download-artifact@v3
        with:
          name: assets
      - name: Create nuget package
        run: dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION --output nupkgs
        working-directory: ./src/Weasyprint.Wrapped
      - name: Push nuget package
        run: dotnet nuget push "Weasyprint.Wrapped.$VERSION.nupkg"  --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"
        working-directory: ./src/Weasyprint.Wrapped/nupkgs
      - name: Upload nuget package
        id: upload-nuget-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/Weasyprint.Wrapped/nupkgs/Weasyprint.Wrapped.$VERSION.nupkg
          asset_name: Weasyprint.Wrapped.$VERSION.nupkg
          asset_content_type: application/zip
      - name: Upload release asset linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: standalone-linux-64.zip
          asset_name: standalone-linux-64.zip
          asset_content_type: application/zip
      - name: Upload release asset windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: standalone-windows-64.zip
          asset_name: standalone-windows-64.zip
          asset_content_type: application/zip
  